services:
  web:
    image: ghcr.io/icpcplatform/icpc-platform:latest
    env_file: .web-env
    ports:
      - "8000:3000"
    deploy:
      replicas: 1
    networks:
      - web_network

networks:
  web_network:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.100.0/24
