services:
  web:
    image: ghcr.io/icpcplatform/icpc-platform:latest
    env_file: .web-env
    volumes:
      - /var/app:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "8000:3000"
    deploy:
      replicas: 1
    network_mode: host

