### Signup
POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "username": "omar",
    "password": "12345678",
}

### Login
POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123",
    "action": "login"
} 
