const departments = [
        "Civil Engineering",
        "Mechanical Engineering",
        "Electrical Engineering",
        "Computer Engineering",
        "Architecture",
        "Mechatronics Engineering",
        "General Medicine",
        "Surgery",
        "Pediatrics",
        "Radiology",
        "Anesthesia",
        "Accounting",
        "Business Administration",
        "Economics",
        "Finance",
        "Marketing",
        "Mathematics",
        "Physics",
        "Chemistry",
        "Biology",
        "Geology",
        "Biotechnology",
        "Criminal Law",
        "Civil Law",
        "International Law",
        "Commercial Law",
        "Computer Science",
        "Artificial Intelligence",
        "Information Systems",
        "Cybersecurity",
        "Data Science",
        "Clinical Pharmacy",
        "Pharmaceutical Chemistry",
        "Pharmacology",
        "Pharmacognosy",
        "Oral Surgery",
        "Orthodontics",
        "Endodontics",
        "Prosthodontics",
        "Philosophy",
        "Psychology",
        "History",
        "Geography",
        "Sociology",
         "Software Engineering",
        "Linguistics",
        "Journalism",
        "Radio and Television",
        "Public Relations",
        "English",
        "French",
        "German",
        "Spanish",
        "Chinese",
        "Japanese",
    ] as const;

export default departments;
