name: pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/icpcplatform/icpc-platform:latest
            ghcr.io/icpcplatform/icpc-platform:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          echo "${{ secrets.WEB_ENV }}" >> .stack-env
          echo "GIT_SHA=${{ github.sha }}" >> .stack-env

      - name: Docker Stack Deploy
        uses: kitconcept/docker-stack-deploy@v1.0.1
        with:
          registry: "ghcr.io"
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          stack_name: web
          stack_file: docker-stack.yaml
          remote_host: ${{ secrets.HOST }}
          remote_user: github-deploy
          remote_private_key: ${{ secrets.SSHKEY }}
          env_file: .stack-env
